// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0vt2Dzkj7O7LpOcwjhwjdMUCYO0R5qRc',
    appId: '1:590116290152:web:c2f73132f2258ea39d05dd',
    messagingSenderId: '590116290152',
    projectId: 'livros-8e2e3',
    authDomain: 'livros-8e2e3.firebaseapp.com',
    storageBucket: 'livros-8e2e3.appspot.com',
    measurementId: 'G-CJ2894W8T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkhlJeut0cDaXANe2oDgb0T4rp0IoxmIc',
    appId: '1:590116290152:android:7b3fbd35e97b246e9d05dd',
    messagingSenderId: '590116290152',
    projectId: 'livros-8e2e3',
    storageBucket: 'livros-8e2e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_EASVEBpc5vQMXFupEbYZkj3t0jeZcU',
    appId: '1:590116290152:ios:53780220433788a09d05dd',
    messagingSenderId: '590116290152',
    projectId: 'livros-8e2e3',
    storageBucket: 'livros-8e2e3.appspot.com',
    iosClientId: '590116290152-vn0n7r45lank6e6kd0eonitk7n72i3d1.apps.googleusercontent.com',
    iosBundleId: 'github.comlucasmenchon.crudBiblioteca01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_EASVEBpc5vQMXFupEbYZkj3t0jeZcU',
    appId: '1:590116290152:ios:53780220433788a09d05dd',
    messagingSenderId: '590116290152',
    projectId: 'livros-8e2e3',
    storageBucket: 'livros-8e2e3.appspot.com',
    iosClientId: '590116290152-vn0n7r45lank6e6kd0eonitk7n72i3d1.apps.googleusercontent.com',
    iosBundleId: 'github.comlucasmenchon.crudBiblioteca01',
  );
}
